import { readFileSync } from "fs";

const testing = true;
const dataTxt = (testing ?
	`.|...\\....
|.-.\\.....
.....|-...
........|.
..........
.........\\
..../.\\\\..
.-.-/..|..
.|....-|.\\
..//.|....
`: readFileSync(__dirname + "/data.txt", "utf-8")).trim().split("\n").map(v => v.split(""));
