import { readFileSync } from "fs";

const dataTxt = `...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....
`.split("\n");
//const dataTxt = readFileSync(__dirname + "/data.txt", "utf-8").split("\n");

